project/home/views.py
from flask import Blueprint, render_template
home_blueprint = Blueprint('home', __name__, template_folder='templates', static_folder='static')

@home_blueprint.route('/')
def index():
    return render_template('home.html')

project/scraper/views.py
# import module
import codecs
import csv
import glob
import io
import json
import os
import re
import time

import gspread
import pandas as pd
import requests
from bs4 import BeautifulSoup
from flask import Blueprint, redirect, url_for, render_template, request, send_from_directory, Response
# configure blueprint
# from project import app
from sqlalchemy import text

from project import db
from project.models.models import Records

# blueprint
scraper_blueprint = Blueprint('scraper', __name__, template_folder='templates')

# data site
base_url = 'https://www.yell.com'

# headers
headers = {
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36'
}


# get total pages function
def get_total_page(keyword, location):
    params = {
        'keywords': keyword,
        'location': location,
        'scrambleSeed': '1189397696',
    }

    # url site
    url = 'https://www.yell.com/ucs/UcsSearchAction.do?'
    req = requests.get(url=url, params=params, headers=headers)
    soup = BeautifulSoup(req.text, 'html.parser')
    try:
        pagination = soup.find('nav', attrs={'class': 'row'}).findAll('a', attrs={'class': 'btn'})
    except:
        pagination = soup.find('nav', attrs={'class': 'row pagination'}).findAll('a', attrs={'class': 'btn'})

    total = len(pagination)
    return total


# function to get all url per page
def get_url_per_page(page, keyword, location):
    data_link = []
    params = {
        'keywords': keyword,
        'location': location,
        'pageNum': page

    }

    url = 'https://www.yell.com/ucs/UcsSearchAction.do?'
    req = requests.get(url, params=params, headers=headers)
    soup = BeautifulSoup(req.text, 'html.parser')
    product_Link = soup.findAll('div', attrs={'class': 'row businessCapsule--mainRow'})
    for item in product_Link:
        link = item.find('div', attrs={'class': 'businessCapsule--titSpons'}).find('a')['href']
        data_link.append(link)

    return data_link


# add counter to rotating vpn if IP Blocked
counter = 0


def get_detail(url):
    global counter, address, city, postal_code

    # request url
    req = requests.get(base_url + url, headers=headers)

    # handling error with html
    f = open(file='./project/scraper/temp/test.html', mode='w+')
    f.write(req.text)

    # read for html in temp directory
    reader = codecs.open(filename='./project/scraper/temp/test.html', mode='r').read()
    parser = BeautifulSoup(reader, 'html.parser')
    try:
        title_text = parser.find('title').text.strip()
    except:
        title_text = parser.find('h1', attrs={'class':'text-h1 businessCard--businessName'})
    # cheking if error
    while 'Are you human?' in title_text:
        with open(file='./project/scraper/server_list/vpn.txt') as data_server:
            vpn_list = data_server.readlines()
            server_list = []
            for vpn in vpn_list:
                server_list.append(vpn.strip())

            # rotating vpn
            try:
                print('Try VPN Server... {}'.format(server_list[counter]))
                os.system('windscribe connect {}'.format(server_list[counter]))
                counter += 1
                break
            except UnboundLocalError:
                continue

    print('Getting Detail URL: {}'.format(url))

    # request URL
    req = requests.get(base_url + url, headers=headers)

    # parsing content from site
    soup = BeautifulSoup(req.text, 'html.parser')

    # get content
    try:
        title = soup.find('h1', attrs={'class': 'text-h1 businessCard--businessName'}).text.strip()
    except:
        title = soup.find('div', attrs={'class': 'text-h1 businessCard--businessName'})

    more_info = soup.findAll('span', attrs={'class': 'address'})
    for info in more_info:
        address = info.find('span', attrs={'itemprop': 'streetAddress'}).text.strip()
        city = info.find('span', attrs={'itemprop': 'addressLocality'}).text.strip()
        postal_code = info.find('span', attrs={'itemprop': 'postalCode'}).text.strip()

    try:
        website = soup.find('a', attrs={'class': 'btn btn-big btn-yellow businessCard--callToAction'})['href']
        telp = soup.find('span', attrs={'class': 'business--telephoneNumber'}).text.strip()
    except:
        website = 'No Website'
        telp = 'No Telephone'

    data_detail = {
        'title': title,
        'address': address,
        'city': city,
        'postal Code': postal_code,
        'telp': telp,
        'website': website
    }

    return data_detail


# route for scraping
@scraper_blueprint.route('/get-url', methods=['GET', 'POST'])
def get_url():
    if request.method == 'POST':
        keyword = request.form['keyword']
        location = request.form['location']

        total_pages = get_total_page(keyword=keyword, location=location)

        data_link = []
        for page in range(total_pages):
            page += 1
            url_per_page = get_url_per_page(keyword=keyword, location=location, page=page)
            data_link += url_per_page

        # extract the url
        result = []
        for url in data_link:
            result.append(url)

        url_count = len(result)

        # get all url
        data_url = {
            'url_list': result
        }

        with open('./project/scraper/result/urls.json', 'w') as url_json:
            json.dump(data_url, url_json)
        print('json generated')
        return render_template('index.html', datas=data_url['url_list'], url_count=url_count)
    return render_template('index.html')


# helper to create to csv and sorted json file
def add_to_sheet():
    gc = gspread.service_account(filename='credentials.json')
    sheets = gc.open_by_key('12ImQ4M4IGYLaQFZY8gRDQcF7Lb_dB99VwsWbv3qTUhQ')
    # read worksheet on drive
    worksheet = sheets.sheet1  # why sheet1 because in this case we only have one sheet
    scrap_res = sorted(glob.glob('./project/scraper/result/downloaded_json/*.json'), key=lambda x: float(re.findall("(\d)", x)[0]))
    scrap_datas = []
    for scrap in scrap_res:
        print('generating JSON: ', scrap)
        with open(scrap) as json_file:

            datas = json.load(json_file)
        scrap_datas.append(datas)

    df = pd.DataFrame(scrap_datas)
    worksheet.update([df.columns.values.tolist()] + df.values.tolist())
    print('Upload Complete')



@scraper_blueprint.route('/view_data')
def view_data():
    records = Records.query.all()

    return render_template('view_data.html', records=records)


# create route to generated json for detail page
@scraper_blueprint.route('/generate_json', methods=['GET', 'POST'])
def generate_json():
    if request.method == 'POST':
        start = request.form['start_list']
        endlist = request.form['end_list']

        start = int(start)
        endlist = int(endlist)

        # read json file from urls,json in result folder
        with open('./project/scraper/result/urls.json', 'r') as read_json:
            datas = json.load(read_json)

        # get input for start generate josn file in download_jon directory
        urls = datas['url_list']
        urls = urls[start:endlist]

        # loop for get file generated json
        for id, url, in enumerate(urls):
            time.sleep(1)
            print('Generated Json File: {} of {}'.format(start + id + 1, endlist))
            data_dict = get_detail(url)

            # generated json file then save to directory
            with open('./project/scraper/result/downloaded_json/{}.json'.format(start + id + 1), 'w') as files:
                json.dump(data_dict, files)
            print('generated json complete')

            # display list with sorteed json
            files = sorted(glob.glob('./project/scraper/result/downloaded_json/*.json'),
                           key=lambda x: float(re.findall("(\d)", x)[0]))
            all_datas = []
            for file in files:
                # read file
                print('sorted file json ', file)
                with open(file) as json_file:
                    datas = json.load(json_file)
                all_datas.append(datas)

            # data dictionary
            url_data = {
                'data_url':all_datas
            }

            # save to database
            try:
                db.session.execute(text(
                    'TRUNCATE TABLE records RESTART IDENTITY;'
                ))


                for value in url_data['data_url']:
                    title = value['title']
                    address = value['address']
                    city = value['city']
                    postal_code = value['postal Code']
                    telp = value['telp']
                    website = value['website']

                    # save to database
                    new_records = Records(title=title, address=address, city=city, postal_code=postal_code, telp=telp, website=website)
                    db.session.add(new_records)
                    db.session.commit()

                add_to_sheet()


            except Exception:
                db.session.rollback()







            # drop table before save to database
            # try:
            #     db.session.execute(
            #         text('TRUNCATE TABLE records RESTART IDENTITY;')
            #     )
            #
            #     for value in values:
            #         title = value['title']
            #         address = value['address']
            #         city = value['city']
            #         postal_code = value['postal Code']
            #         telp = value['telp']
            #         website = value['website']
            #
            #         # save to database
            #         new_records = Records(title=title, address=address, city=city, postal_code=postal_code, telp=telp,
            #                               website=website)
            #         db.session.add(new_records)

project/home/templates/home.html
{% extends "theme.html" %}

{% block page_title %}
  Home Page Yell Scraper
{% endblock page_title %}

{% block contents %}
    <!-- ======= Hero Section ======= -->
  <section id="hero">
    <div class="hero-container">
      <div id="heroCarousel" class="carousel slide carousel-fade" data-ride="carousel">

        <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

        <div class="carousel-inner" role="listbox">

          <!-- Slide 1 -->
          <div class="carousel-item active">
            <div class="carousel-background"><img src="{{ url_for('static', filename='assets/img/slide/slide-1.jpg') }}" alt=""></div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2 class="animate__animated animate__fadeInDown">Welcome to <span>Yell Scraper</span></h2>
                <p class="animate__animated animate__fadeInUp">Scrape Data from yell for your company free and easily</p>
                <a href="{{ url_for('home.index') }}" class="btn-get-started animate__animated animate__fadeInUp scrollto">Try This</a>
              </div>
            </div>
          </div>

          <!-- Slide 2 -->
          <div class="carousel-item">
            <div class="carousel-background"><img src="{{ url_for('static', filename='assets/img/slide/slide-2.jpg') }}" alt=""></div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2 class="animate__animated animate__fadeInDown">View Our Service </h2>
                <p class="animate__animated animate__fadeInUp">just scroll down</p>
                <a href="#" class="btn-get-started animate__animated animate__fadeInUp scrollto">Or Click Here</a>
              </div>
            </div>
          </div>

          <!-- Slide 3 -->
          <div class="carousel-item">
            <div class="carousel-background"><img src="{{ url_for('static', filename='assets/img/slide/slide-3.jpg') }}" alt=""></div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2 class="animate__animated animate__fadeInDown">What is Yellowpages or yell.com</h2>
                <p class="animate__animated animate__fadeInUp">yellow pages are any telephone directory of businesses, organized by category rather than alphabetically by business name, and in which advertising is sold. ... The traditional term "yellow pages" is now also applied to online directories of businesses.</p>
                <a href="https://yell.com" target="blank" class="btn-get-started animate__animated animate__fadeInUp scrollto">Visit Site</a>
              </div>
            </div>
          </div>

        </div>

        <a class="carousel-control-prev" href="#heroCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon icofont-thin-double-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>

        <a class="carousel-control-next" href="#heroCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon icofont-thin-double-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>

      </div>
    </div>
  </section>
  <!-- end section -->

  <!-- ======= About Us Section ======= -->
  <section id="about" class="about">
    <div class="container">

      <div class="section-title">
        <h2>About Our Service</h2>
        <p>Our Service can Help You to Scrape for your company</p>
      </div>

      <div class="row">
        <div class="col-lg-6">
          <img src="{{ url_for('static', filename='assets/img/about.jpg') }}" class="img-fluid" alt="">
        </div>
        <div class="col-lg-6 pt-4 pt-lg-0 content">
          <h3> This App Build With<strong> python programming language</strong></h3>
          <p class="font-italic">
            our service can you try for free forever
          </p>
          <p>
            The original source to find and connect with local plumbers, handymen, mechanics, attorneys, dentists, and more.
          </p>

          <div class="skills-content">

            <div class="progress">
              <span class="skill">HTML <i class="val">20%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>

            <div class="progress">
              <span class="skill">CSS <i class="val">20%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>

            <div class="progress">
              <span class="skill">Python <i class="val">30%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>

            <div class="progress">
              <span class="skill">Flask <i class="val">50%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>

          </div>

        </div>
      </div>

    </div>
  </section>

  <!-- end about us -->

<!-- ======= Our Services Section ======= -->
   <section id="services" class="services">
    <div class="container">

      <div class="section-title">
        <h2>Our Services</h2>
        <p>Try Our Service is free</p>
      </div>

      <div class="row">
        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
          <div class="icon-box">
            <div class="icon"><i class="bx bxl-dribbble"></i></div>
            <h4 class="title"><a href="{{ url_for('scraper.get_url') }}">URL Generator</a></h4>
            <p class="description">can Get Url just Click One Button</p>
          </div>
        </div>

        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
          <div class="icon-box">
            <div class="icon"><i class="bx bx-file"></i></div>
            <h4 class="title"><a href="{{ url_for('scraper.generate_json') }}">Generating All Detail from site</a></h4>
            <p class="description">Can Generating Data for your company</p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End Our Services Section -->

{% endblock contents %}

project/home/templates/theme.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Favicon -->
  <link href="{{ url_for('static', filename='assets/img/favicon.png') }}" rel="icon">
  <link href="{{ url_for('static', filename='assets/img/apple-touch-icon.png') }}" rel="apple-touch-icon">

  <!-- Vendor CSS Files -->
  <link href="{{ url_for('static', filename='assets/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='assets/vendor/icofont/icofont.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='assets/vendor/boxicons/css/boxicons.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='assets/vendor/animate.css/animate.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='assets/vendor/owl.carousel/assets/owl.carousel.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='assets/vendor/venobox/venobox.css') }}" rel="stylesheet">
  
  <!-- Template Main CSS File -->
  <link href="{{ url_for('static', filename='assets/css/style.css') }}" rel="stylesheet">

     <!-- Bootstrap CSS -->
     <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous"> -->


    <title>
        {% block page_title %}
          
        {% endblock page_title %}
    </title>
</head>
<body>
    <!-- navbar section -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{{ url_for('home.index') }}">Yell Scraper</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{{ url_for('home.index') }}">Home</a>
                <a class="nav-link" href="{{ url_for('scraper.generate_json') }}">Generated Json File</a>
                <a class="nav-link" href="{{ url_for('scraper.view_data') }}">View Data Result</a>
                <a class="nav-link" href="{{ url_for('scraper.get_url') }}" tabindex="-1" aria-disabled="false">Generate URL</a>
              </div>
          </div>
        </div>
      </nav>
    <!-- end navbar section -->

    {% block contents %}
      
    {% endblock contents %}
     <!-- Optional JavaScript -->
    <!-- Popper.js first, then Bootstrap JS -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script> -->

    <!-- Javascript sources -->

  <script src="{{ url_for('static', filename='assets/vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='assets/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
  <script src="{{ url_for('static', filename='assets/vendor/jquery.easing/jquery.easing.min.js') }}"></script>
  <script src="{{ url_for('static', filename='assets/vendor/jquery-sticky/jquery.sticky.js') }}"></script>
  <script src="{{ url_for('static', filename='assets/vendor/waypoints/jquery.waypoints.min.js') }}"></script>
  <script src="{{ url_for('static', filename='assets/vendor/counterup/counterup.min.js') }}"></script>
  <script src="{{ url_for('static', filename='assets/vendor/isotope-layout/isotope.pkgd.min.js') }}"></script>
  <script src="{{ url_for('static', filename='assets/vendor/owl.carousel/owl.carousel.min.js') }}"></script>
  <script src="{{ url_for('static', filename='assets/vendor/venobox/venobox.min.js') }}"></script>

  <!-- Template Main JS File -->
  <script src="{{ url_for('static', filename='assets/js/main.js') }}"></script>
</body>
</html>